/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
// import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

export default function Home() {
  const [forceRender, setForceRender] = useState(false);

  useEffect(() => {
    setForceRender(true);
  }, []);

  useEffect(() => {
    document
      .querySelector(".mainContainer")
      .classList.toggle("changeLeftRight");
  }, [forceRender]);

  return (
    <>
      <Head>
        <title>React Form Hook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ position: "relative" }}>
        <div className="mainContainer">
          <div className="innerBg"/>
          <div className="outerBg"/>
        </div>
      </main>
    </>
  );
}
